#!/bin/sh

SUBFOLDER="bin"
EXECUTABLE="generator"

SPHERE_ARGS="sphere 1 20 20 sphere.3d"
CONE_ARGS="cone 1 2 20 20 cone.3d"
CYLINDER_ARGS="cylinder 1 2 20 20 cylinder.3d"
TORUS_ARGS="torus 0.5 0.25 20 20 torus.3d"
BOX_ARGS="box 1 3 box.3d"
PLANE_ARGS="plane 1 3 plane.3d"


"./$SUBFOLDER/$EXECUTABLE" $SPHERE_ARGS
"./$SUBFOLDER/$EXECUTABLE" $CONE_ARGS
"./$SUBFOLDER/$EXECUTABLE" $CYLINDER_ARGS
"./$SUBFOLDER/$EXECUTABLE" $TORUS_ARGS
"./$SUBFOLDER/$EXECUTABLE" $BOX_ARGS
"./$SUBFOLDER/$EXECUTABLE" $PLANE_ARGS